<a href="https://colab.research.google.com/github/leejuny0ng/AI/blob/main/AI%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk
nltk.download('punkt')

from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

stemmer = PorterStemmer()

sentence = "This was not the map we found in Billy Bones's chest, but an accurate copy, complete in all things--names and heights and soundings--with the single exception of the red crosses and the written notes. analyze formailize utilize utilization facility humanity humiliation humidity balance"
tokenized_sentence = word_tokenize(sentence)

print('어간 추출 전 :', tokenized_sentence)
print('어간 추출 후 :',[stemmer.stem(word) for word in tokenized_sentence])


어간 추출 전 : ['This', 'was', 'not', 'the', 'map', 'we', 'found', 'in', 'Billy', 'Bones', "'s", 'chest', ',', 'but', 'an', 'accurate', 'copy', ',', 'complete', 'in', 'all', 'things', '--', 'names', 'and', 'heights', 'and', 'soundings', '--', 'with', 'the', 'single', 'exception', 'of', 'the', 'red', 'crosses', 'and', 'the', 'written', 'notes', '.', 'analyze', 'formailize', 'utilize', 'utilization', 'facility', 'humanity', 'humiliation', 'humidity', 'balance']
어간 추출 후 : ['thi', 'wa', 'not', 'the', 'map', 'we', 'found', 'in', 'billi', 'bone', "'s", 'chest', ',', 'but', 'an', 'accur', 'copi', ',', 'complet', 'in', 'all', 'thing', '--', 'name', 'and', 'height', 'and', 'sound', '--', 'with', 'the', 'singl', 'except', 'of', 'the', 'red', 'cross', 'and', 'the', 'written', 'note', '.', 'analyz', 'formail', 'util', 'util', 'facil', 'human', 'humili', 'humid', 'balanc']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
import nltk
import konlpy
nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from konlpy.tag import Okt

stop_words_list = stopwords.words('english')
print('불용어 개수 :', len(stop_words_list))
print('불용어 10개 출력 :',stop_words_list[:50])



불용어 개수 : 179
불용어 10개 출력 : ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
!pip install konlpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 67.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 23.9 MB/s eta 0:00:00


In [ ]:
example = "Family is not an important thing. It's everything."
stop_words = set(stopwords.words('english'))

word_tokens = word_tokenize(example)

result = []

for word in word_tokens:
  if word not in stop_words: # 불용어 아닌것을 result 배열에 추가
    result.append(word)

print("불용어 제거 전:", word_tokens)
print("불용어 제거 후:", result)

불용어 제거 전: ['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
불용어 제거 후: ['Family', 'important', 'thing', '.', 'It', "'s", 'everything', '.']


In [ ]:
okt = Okt()

example = "고기를 아무렇게나 구우려고 하면 안 돼. 고기라고 다 같은 게 아니거든. 예컨대 삼겹살을 구울 때는 중요한 게 있지."
stop_words = "를 아무렇게나 구 우려 고 안 돼 같은 게 구울 때 는"

stop_words = set(stop_words.split(' '))
word_tokens = okt.morphs(example)

result = [word for word in word_tokens if not word in stop_words]

print('불용어 제거 전 :',word_tokens)
print('불용어 제거 후 :',result)


불용어 제거 전 : ['고기', '를', '아무렇게나', '구', '우려', '고', '하면', '안', '돼', '.', '고기', '라고', '다', '같은', '게', '아니거든', '.', '예컨대', '삼겹살', '을', '구울', '때', '는', '중요한', '게', '있지', '.']
불용어 제거 후 : ['고기', '하면', '.', '고기', '라고', '다', '아니거든', '.', '예컨대', '삼겹살', '을', '중요한', '있지', '.']


In [ ]:
import re

r = re.compile("a.c")
r.search("aBBc")
# .는 한 개의 임의의 문자가 올 수 있음 (\n은 제)
# 위는 한개의 문자가 아니므로 아무것도 출력되지 않음
r.search("a$c")
# 위는 한 개의 문자가 들어가므로 match 된다

<re.Match object; span=(0, 3), match='a$c'>

In [ ]:
r = re.compile("ab?c")
# ?는 ? 앞의 문자(이 예제에서는 b가 됨)가 존재할 수도 있고 존재하지 않을 수도 있는 경우를 나타냄
r.search("abbc")
# 위는 a와 c 사이에 (b 이외의) 문자가 2개 이상 존재하므로 아무런 결과가 출력되지 않는다

r.search("acc")

<re.Match object; span=(0, 2), match='ac'>

In [ ]:
r.search("abc")

<re.Match object; span=(0, 3), match='abc'>

In [ ]:
r.search("ac")

<re.Match object; span=(0, 2), match='ac'>

정규화

In [ ]:
s = "I visited UK from US on 22-09-20"
print(s)

I visited UK from US on 22-09-20


In [ ]:
new_s = s.replace("UK", "United Kingdom").replace("US", "United States").replace("-20", "-2020")
print(new_s)

I visited United Kingdom from United States on 22-09-2020


a\


정규표현식
- 정규 표현식은 특정 문자들을 편리하게 지정하고 추가 및 삭제가 가능
- 데이터 전처리에서 정규 표현식을 많이 사용
- 파이썬에서는 정규 표현식을 지원하는 re 패키지 제공

In [ ]:
import re
check = "ab."
# 하나의 문자
print(re.match(check, 'abc'))
print(re.match(check, 'c'))
print(re.match(check, 'ab'))
print(re.match(check, 'abbc'))

<re.Match object; span=(0, 3), match='abc'>
None
None
<re.Match object; span=(0, 3), match='abb'>


compile
- compile을 사용하면 여러 번 사용할 경우 일반 사용보다 더 빠른 속도를 보임
- compile을 통해 정규 표현식을 사용할 경우 re가 아닌 컴파일한 객체 이름을 통해 사용해야 함

In [ ]:
import time

normal_s_time = time.time() # 시간 설정
r = 'ab.'
for i in range(1000):
  re.match(check, 'abc')
print('일반 사용 시 소요 시간:', time.time() - normal_s_time)

compile_s_time = time.time()

r = re.compile('ab.')
for i in range(1000):
  r.match(check)
print('compile 사용시', time.time() - compile_s_time)

# compile 사용 시간 <<<< 일반 사용 시간
# 반복문 사용시 compile 사용할 것

일반 사용 시 소요 시간: 0.0018312931060791016
compile 사용시 0.0007686614990234375


search
- match는 한 단어만 확인하는 반면, search는 문자열의 전체 검사

In [ ]:
check = 'ab?'
# ? 앞에 문자가 있는지 또는 없는지를 나타냄
print(re.search("a",check))
# ab에 b가 없으면 a가 되기에 match
print(re.match('kkkab',check))
# kkk는 기존 check에 존재하지 않는 문자이므로 match되지 않음
print(re.search("kkkab", check))
# 상동
print(re.match('ab', check))
# ab에 b가 있는 ab기에 match


<re.Match object; span=(0, 1), match='a'>
None
None
<re.Match object; span=(0, 2), match='ab'>


split
- 정규표현식에 해당하는 문자열을 기준으로 문자열을 나눔


In [ ]:
r = re.compile(' ')
print(r.split('abc abbc abcbab'))
# ' ' 공백이 컴파일 되었기에 abc abbc abcbab를 리턴
r = re.compile('c')
print(r.split('abc abbc abcbab'))
# c를 기준으로 compile 된것이기에 ab abb ab bab를 리턴

r = re.compile('[0-9]') # 0부터 9까지 모두 (정수 기준)
print(r.split("slabc 2v3s 4sss 5a"))
# 숫자를 기준으로 comiple 한 것으로  slabc v s sss a 를 리턴

['abc', 'abbc', 'abcbab']
['ab', ' abb', ' ab', 'bab']
['slabc ', 'v', 's ', 's', 'ss ', 'a']


sub
- 정규표현식과 일치하는 부분을 다른 문자열로 교체


In [ ]:
print(re.sub('[a-z]', '1', 'abcdefg'))
# 영어에 해당된다면 그냥 1로 만들어라
print(re.sub('[^a-z]', '1', 'abc defg'))
# 알파벳에 해당되지 않는다면 1로 만드는 것, 공백은 해당되지 않으니 abc1defg가 나올 것

1111111
abc1defg


findall
- 컴파일한 정규표현식을 이용해 정규 표현식과 맞는 모든 문자열을 리스트로 변환

In [ ]:
print(re.findall('[\d]', '1ab 2cd 3ef 4g'))
# d는 decimal (정수를 뽑음) >> 1, 2, 3, 4를 출력할 것

print(re.findall('[\W]', '!abcd@@#'))
# W는 문자또는 숫자가 아닌 문자(특수문자) >> !, @, @, # 를 출력할 것

['1', '2', '3', '4']
['!', '@', '@', '#']


finditer
- 컴파일한 정규표현식을 이용해 정규 표현식과 맞는 모든 문자(열)을 `iterator` 객체로 반환
- `iterator` 객체를 이용하면 생성된 객체를 하나씩 자동으로 가져올 수 있어 처리가 간편

In [ ]:
iter1 = re.finditer('[\d]', '1ab 2cd 3ef 4g')
print(iter1)
for i in iter1:
  print(i)

iter2 = re.finditer('[\W]', '!abcd@@#')
print(iter2)
for i in iter2:
  print(i)

<re.Match object; span=(0, 1), match='1'>
<re.Match object; span=(4, 5), match='2'>
<re.Match object; span=(8, 9), match='3'>
<re.Match object; span=(12, 13), match='4'>
<re.Match object; span=(0, 1), match='!'>
<re.Match object; span=(5, 6), match='@'>
<re.Match object; span=(6, 7), match='@'>
<re.Match object; span=(7, 8), match='#'>


In [ ]:
sentence = 'Time is gold'
tokens = [x for x in sentence.split(' ')]
tokens

['Time', 'is', 'gold']

In [ ]:
import nltk
nltk.download('punkt')

from nltk.tokenize import word_tokenize

tokens = word_tokenize(sentence)
tokens

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


['Where', 'there', "'s", 'a', 'will', ',', 'there', "'s", 'a', 'way']

In [ ]:
sentences = 'The world is a beautiful book.\nBut of little use to him who cannot read it'
print(sentences)

tokens = [x for x in sentences.split('\n')]
tokens

The world is a beautiful book.
But of little use to him who cannot read it


['The world is a beautiful book.',
 'But of little use to him who cannot read it']

In [ ]:
from nltk.tokenize import sent_tokenize

tokens = sent_tokenize(sentences)
tokens
#sent_ tokenize 는 문장 단위로 토큰화를 해줌


['The world is a beautiful book.',
 'But of little use to him who cannot read it']

정규표현식을 이용한 토큰화
- 토큰화 기능을 직접 구현할 수도 있지만 정규 표현식을 이용해 간단하게 구현할 수도 있음
- nltk 패키지는 정규 표현식을 사용하는 토큰화 도구인 RegexpTokenizer를 제공

In [ ]:
from nltk.tokenize import RegexpTokenizer

sentence = 'Where there\'s a will, there\'s a way'

tokenizer = RegexpTokenizer('[\w]+') # 특수문자 포함 x
tokens = tokenizer.tokenize(sentence)
print(tokens)

['Where', 'there', 's', 'a', 'will', 'there', 's', 'a', 'way']


In [ ]:
tokenizer = RegexpTokenizer('[\s]+', gaps = True)
tokens = tokenizer.tokenize(sentence)
print(tokens)

# \s 는 공백 기준으로 가름

['Where', "there's", 'a', 'will,', "there's", 'a', 'way']


In [ ]:
!pip install --upgrade tensorflow


케라스


In [ ]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence

sentence = 'Where there\'s a will, there\'s a way'
text_to_word_sequence(sentence)

['where', "there's", 'a', 'will', "there's", 'a', 'way']

In [ ]:

from textblob import TextBlob

sentence = 'Where there\'s a will, there\'s a way'
bob = TextBlob(sentence)
bob.words

WordList(['Where', 'there', "'s", 'a', 'will', 'there', "'s", 'a', 'way'])

In [ ]:
from nltk import ngrams

sentence = 'There is no royal road to learning'
bigram = list(ngrams(sentence.split(), 2))
print(bigram)
# 2단어씩 묶어서 list화함 (겹치는 것 존재)

[('There', 'is'), ('is', 'no'), ('no', 'royal'), ('royal', 'road'), ('road', 'to'), ('to', 'learning')]


In [ ]:
trigram = list(ngrams(sentence.split(), 3))
print(trigram)

[('There', 'is', 'no'), ('is', 'no', 'royal'), ('no', 'royal', 'road'), ('royal', 'road', 'to'), ('road', 'to', 'learning')]


In [ ]:
from textblob import TextBlob

blob = TextBlob(sentence)
blob.ngrams(n=2)

[WordList(['There', 'is']),
 WordList(['is', 'no']),
 WordList(['no', 'royal']),
 WordList(['royal', 'road']),
 WordList(['road', 'to']),
 WordList(['to', 'learning'])]

In [ ]:
blob.ngrams(n=3)

[WordList(['There', 'is', 'no']),
 WordList(['is', 'no', 'royal']),
 WordList(['no', 'royal', 'road']),
 WordList(['royal', 'road', 'to']),
 WordList(['road', 'to', 'learning'])]

POS(Parts of Speech) 태깅
- PoS는 품사로 PoS 태깅은 문장 내에서 단어에 해당하는 각 품사를 태깅

In [ ]:
word = word_tokenize("Think like man of action and act like man of thought.")
word

['Think',
 'like',
 'man',
 'of',
 'action',
 'and',
 'act',
 'like',
 'man',
 'of',
 'thought',
 '.']

In [ ]:
nltk.download('averaged_perceptron_tagger')
nltk.pos_tag(word)
# 품사를 의미하는 태그가 달림

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


[('Think', 'VBP'),
 ('like', 'IN'),
 ('man', 'NN'),
 ('of', 'IN'),
 ('action', 'NN'),
 ('and', 'CC'),
 ('act', 'NN'),
 ('like', 'IN'),
 ('man', 'NN'),
 ('of', 'IN'),
 ('thought', 'NN'),
 ('.', '.')]

In [ ]:
nltk.pos_tag(word_tokenize("A rolling stone gathers no moss"))

[('A', 'DT'),
 ('rolling', 'VBG'),
 ('stone', 'NN'),
 ('gathers', 'NNS'),
 ('no', 'DT'),
 ('moss', 'NN')]

| Number | Tag | Description | 설명 |
| -- | -- | -- | -- |
| 1 | `CC` | Coordinating conjunction |
| 2 | `CD` | Cardinal number |
| 3 | `DT` | Determiner | 한정사
| 4 | `EX` | Existential there |
| 5 | `FW` | Foreign word | 외래어 |
| 6 | `IN` | Preposition or subordinating conjunction | 전치사 또는 종속 접속사 |
| 7 | `JJ` | Adjective | 형용사 |
| 8 | `JJR` | Adjective, comparative | 헝용사, 비교급 |
| 9 | `JJS` | Adjective, superlative | 형용사, 최상급 |
| 10 | `LS` | List item marker |
| 11 | `MD` | Modal |
| 12 | `NN` | Noun, singular or mass | 명사, 단수형 |
| 13 | `NNS` | Noun, plural | 명사, 복수형 |
| 14 | `NNP` | Proper noun, singular | 고유명사, 단수형 |
| 15 | `NNPS` | Proper noun, plural | 고유명사, 복수형 |
| 16 | `PDT` | Predeterminer | 전치한정사 |
| 17 | `POS` | Possessive ending | 소유형용사 |
| 18 | `PRP` | Personal pronoun | 인칭 대명사 |
| 19 | `PRP$` | Possessive pronoun | 소유 대명사 |
| 20 | `RB` | Adverb | 부사 |
| 21 | `RBR` | Adverb, comparative | 부사, 비교급 |
| 22 | `RBS` | Adverb, superlative | 부사, 최상급 |
| 23 | `RP` | Particle |
| 24 | `SYM` | Symbol | 기호
| 25 | `TO` | to |
| 26 | `UH` | Interjection | 감탄사 |
| 27 | `VB` | Verb, base form | 동사, 원형 |
| 28 | `VBD` | Verb, past tense | 동사, 과거형 |
| 29 | `VBG` | Verb, gerund or present participle | 동사, 현재분사 |
| 30 | `VBN` | Verb, past participle | 동사, 과거분사 |
| 31 | `VBP` | Verb, non-3rd person singular present | 동사, 비3인칭 단수 |
| 32 | `VBZ` | Verb, 3rd person singular present | 동사, 3인칭 단수 |
| 33 | `WDT` | Wh-determiner |
| 34 | `WP` | Wh-pronoun |
| 35 | `WP$` | Possessive wh-pronoun |
| 36 | `WRB` | Wh-adverb |



언어 단수화 복수화

In [ ]:
from textblob import TextBlob
words = 'apples bananas oranges'
tb = TextBlob(words)

print(tb.words)
print(tb.words.singularize())
# singluarize -> 단수화

['apples', 'bananas', 'oranges']
['apple', 'banana', 'orange']


In [ ]:
words = 'car train airplane me you water flower pant rain sun'
tb = TextBlob(words)

print(tb.words)
print(tb.words.pluralize())
# pluralize() -> 복수화

['car', 'train', 'airplane', 'me', 'you', 'water', 'flower', 'pant', 'rain', 'sun']
['cars', 'trains', 'airplanes', 'us', 'you', 'water', 'flowers', 'pants', 'rains', 'suns']


개체명 인식(Named Entity Recognition)


In [ ]:
import nltk
from nltk import word_tokenize
nltk.download('maxent_ne_chunker')
nltk.download('words')

[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.


True

In [ ]:
s = 'Rome was not built in a day'
print(s)

Rome was not built in a day


In [ ]:
tags = nltk.pos_tag(word_tokenize(s))
print(tags)

[('Rome', 'NNP'), ('was', 'VBD'), ('not', 'RB'), ('built', 'VBN'), ('in', 'IN'), ('a', 'DT'), ('day', 'NN')]


In [ ]:
entities = nltk.ne_chunk(tags, binary = True)
print(entities)
# Rome 은 NE (NAMED ENTITY)라는 태깅이 붙은것으로 보아 Rome은 개체명이다 라고 유추 가능

(S (NE Rome/NNP) was/VBD not/RB built/VBN in/IN a/DT day/NN)


단어 중의성 (Lexical Ambiguity)

In [ ]:
import nltk
from nltk.wsd import lesk
nltk.download('wordnet')

s = 'I saw bats'
# bat는 박쥐, 방망이등 여러가지 해석이 가능
# saw 또한 see 과거형도 가능하지만, 썰다의 이중적 의미도 가능

print(word_tokenize(s))
print(lesk(word_tokenize(s), 'saw'))
print(lesk(word_tokenize(s), 'bats'))

from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package wordnet to /root/nltk_data...


['I', 'saw', 'bats']
Synset('saw.v.01')
Synset('squash_racket.n.01')


한국어 처리

정규표현식
- 한국어 정규 표현식도 대부분의 문법은 영어 정규 표현식과 같음
- 자음과 모음이 분리되어 있기에 문법을 지정할때는 자음과 모음을 동시에 고려해야함

sub

In [ ]:
print(re.sub('[가-힣]', '1', '가나다라마바사'))
print(re.sub('[^가-힣]', '1', '가나다라마바사'))

1111111
가나다라마바사


In [ ]:
!set -x \
&& pip install konlpy \
&& curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh | bash -x

+ pip install konlpy
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 69.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 32.5 MB/s eta 0:00:00
+ curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh
+ bash -x
+ mecab_dicdir=/usr/local/lib/mecab/dic/mecab-ko-dic
+ set -e
++ uname
+ os=Linux
+ [[ ! Linux == \L\i\n\u\x ]]
+ hash sudo
+ sudo=sudo
+ python=python3
+ hash pyenv
+ at_user_site=
++ check_python_site_location_is_writable
++ python3 -
+ [[ 1 == \0 ]]
+ hash automake
+ hash mecab
+ echo 'Install mecab-ko'
Install mecab-ko
+ install_mecab_ko
+ cd /tmp
+ curl -LO https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1381k  100 1381k    0     0   828k      0  0

In [ ]:
!pip install unroll

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [ ]:
from nltk.tokenize import RegexpTokenizer

sentence = '안녕?하세요 친구들아 저 는 자연어 처리를 배우고싶은 하냥입니다.'
tokenizer = RegexpTokenizer("[가-힣]+")
tokens = tokenizer.tokenize(sentence)
print(tokens)

['안녕', '하세요', '친구들아', '저', '는', '자연어', '처리를', '배우고싶은', '하냥입니다']


BAG OF WORDS(BOW)

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
# count vectorizer = 문서에서 단어의 빈도수를 계산해서 문서 단어 행렬을 만들어주는 작업을 하는 모듈
corpus = ["Think like a man of action and act like man of thought"]

vector = CountVectorizer() # 문서를 벡터표현으로 바꿈
bow = vector.fit_transform(corpus) # 벡터 fit()은 데이터를 학습, transform()은 학습된 데이터를 적용시키는 메서드
# fit_transform은 둘 다

print(bow.toarray())
# 단어들의 개수를 array 형태로 바꾸어준다
print(vector.vocabulary_)
# vector 행렬의 col이 무엇을 의미하는지 보여줌

[[1 1 1 2 2 2 1 1]]
{'think': 6, 'like': 3, 'man': 4, 'of': 5, 'action': 1, 'and': 2, 'act': 0, 'thought': 7}


In [ ]:
vector = CountVectorizer(stop_words='english') # 영어의 불용어 걸러냄
bow = vector.fit_transform(corpus) # corpus의 데이터를 학습 후 적용

print(bow.toarray()) # 단어들의 개수를 array화
print(vector.vocabulary_) # 행렬의 col이 무엇을 의미하는지 보여줌

[[1 1 2 2 1 1]]
{'think': 4, 'like': 2, 'man': 3, 'action': 1, 'act': 0, 'thought': 5}


In [ ]:
# 한글 CASE
corpus = ["평생 살 것처럼 꿈을 꾸어라. 그리고 내일 죽을 것처럼 오늘을 살아라."]

vector = CountVectorizer() # 조사 같은 한 단어짜리는 조사 취급하고 무시해버리기에 다른 방법이 더 효과가 좋을 수 있음
bow = vector.fit_transform(corpus)

print(bow.toarray())
print(vector.vocabulary_)
# 것처럼 2번 등장

[[2 1 1 1 1 1 1 1 1]]
{'평생': 8, '것처럼': 0, '꿈을': 3, '꾸어라': 2, '그리고': 1, '내일': 4, '죽을': 7, '오늘을': 6, '살아라': 5}


In [ ]:
import re
from konlpy.tag import Mecab

tagger = Mecab()
corpus = "평생 살 것처럼 꿈을 꾸어라. 그리고 내일 죽을 것처럼 오늘을 살아라."
tokens = tagger.morphs(re.sub("(\.)", "", corpus))
# 정규화식을 통해 특수기호를 빼고 replace
vocab = {}
bow = []

for tok in tokens:
  if tok not in vocab.keys():
    vocab[tok] = len(vocab)
    bow.insert(len(vocab) - 1, 1)
  else:
    index = vocab.get(tok)
    bow[index] = bow[index] + 1

print(bow)
print(vocab)
# 일일이 단어 하나까지 뽑아서 비교함

[1, 2, 2, 2, 1, 3, 1, 1, 1, 1, 1, 1, 1]
{'평생': 0, '살': 1, '것': 2, '처럼': 3, '꿈': 4, '을': 5, '꾸': 6, '어라': 7, '그리고': 8, '내일': 9, '죽': 10, '오늘': 11, '아라': 12}


문서 단어 행렬 (DTM)
- 문서 단어 행렬은 문서에 등장하는 여러 단어들의 빈도를 행렬로 표현
- 각 문서에 대한 BoW (Bag of Words)를 하나의 행렬로 표현한 것

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = ["Think like a man of action and act like man of thought.",
          "Try not to become a man of success but rather try to become a man of value.",
          "Give me liberty, of give me death"]

vector = CountVectorizer(stop_words = 'english')
bow = vector.fit_transform(corpus)

print(bow.toarray())
print(vector.vocabulary_)

[[1 1 0 0 2 2 0 1 1 0 0]
 [0 0 0 0 0 2 1 0 0 2 1]
 [0 0 1 1 0 0 0 0 0 0 0]]
{'think': 7, 'like': 4, 'man': 5, 'action': 1, 'act': 0, 'thought': 8, 'try': 9, 'success': 6, 'value': 10, 'liberty': 3, 'death': 2}


In [ ]:
!apt-get update
!apt-get install g++ openjdk-8-jdk
!pip3 install konlpy JPype1-py3
!bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)

Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Hit:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Ign:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Get:7 https://r2u.stat.illinois.edu/ubuntu jammy Release [5,713 B]
Get:8 https://r2u.stat.illinois.edu/ubuntu jammy Release.gpg [793 B]
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:10 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,153 kB]
Hit:11 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [3,186 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [2,308 kB]
Hit:14 https://

In [ ]:
!apt-get install -y mecab libmecab-dev mecab-ipadic-utf8
!pip install mecab-python3


Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libmecab2 mecab-ipadic mecab-utils
The following NEW packages will be installed:
  libmecab-dev libmecab2 mecab mecab-ipadic mecab-ipadic-utf8 mecab-utils
0 upgraded, 6 newly installed, 0 to remove and 55 not upgraded.
Need to get 7,367 kB of archives.
After this operation, 59.3 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libmecab2 amd64 0.996-14build9 [199 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libmecab-dev amd64 0.996-14build9 [306 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 mecab-utils amd64 0.996-14build9 [4,850 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 mecab-ipadic all 2.7.0-20070801+main-3 [6,718 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/universe amd64 mecab amd64 0.996-14build9 [136 kB]
Get:6 http://archive.ubuntu.co

In [ ]:
pip install --upgrade setuptools

  Using cached setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
Using cached setuptools-75.1.0-py3-none-any.whl (1.2 MB)
  Attempting uninstall: setuptools
    Found existing installation: setuptools 71.0.4
    Uninstalling setuptools-71.0.4:
      Successfully uninstalled setuptools-71.0.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.


In [ ]:
!pip install --upgrade setuptools

In [ ]:
!pip install ez_setup

In [20]:
import pandas as pd
import numpy as np

columns = []
for k, v in sorted(vector.vocabulary_.items(), key = lambda item:item[1]):
  columns.append(k)

df = pd.DataFrame(bow.toarray(), columns = columns)
df

act  action  death  liberty  like  man  success  think  thought  try  value
0    1       1      0        0     2    2        0      1        1    0      0
1    0       0      0        0     0    2        1      0        0    2      1
2    0       0      1        1     0    0        0      0        0    0      0

어휘 빈도 - 문서 역빈도 분석 (TF-IDF; Term Frequency-Inverse Document Frequency)
- 많이 나온 단어가 그 단어가 특정 문서의 핵심 단어가 아닐 수도 있다는 것
- 단순히 빈도수가 높은 단어가 아닌, 특정 문서에서만 많이 나온 단어라면 핵심 단어로 간주
- TF-IDF = 어휘 빈도 * 역문서 빈도
- 어휘 빈도는 특정 문서에서 특정 단어가 많이 등장하는 것을 의미
$$ tf_{x,y} $$
- 역문서 빈도는 다른 문서에서 등장하지 않는 단어 빈도를 의미
$$ log(N/df_x) $$      
- TF-IDF는 다음과 같이 표현
$$ W_{x,y} = tf_{x,y} * log(N/df_x) $$

- TF-IDF를 편리하게 계산하기 위해  scikit-learn의 tfidfvectorizer를 이용

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words = 'english').fit(corpus)

print(tfidf.transform(corpus).toarray())
print(tfidf.vocabulary_)

[[0.311383   0.311383   0.         0.         0.62276601 0.4736296
  0.         0.311383   0.311383   0.         0.        ]
 [0.         0.         0.         0.         0.         0.52753275
  0.34682109 0.         0.         0.69364217 0.34682109]
 [0.         0.         0.70710678 0.70710678 0.         0.
  0.         0.         0.         0.         0.        ]]
{'think': 7, 'like': 4, 'man': 5, 'action': 1, 'act': 0, 'thought': 8, 'try': 9, 'success': 6, 'value': 10, 'liberty': 3, 'death': 2}


In [19]:
columns = []
for k,v in sorted(tfidf.vocabulary_.items(), key = lambda item:item[1]):
  columns.append(k)

pd.DataFrame(tfidf.transform(corpus).toarray(), columns = columns)
# 가시성 좋게 DataFrame화

act    action     death   liberty      like       man   success  \
0  0.311383  0.311383  0.000000  0.000000  0.622766  0.473630  0.000000   
1  0.000000  0.000000  0.000000  0.000000  0.000000  0.527533  0.346821   
2  0.000000  0.000000  0.707107  0.707107  0.000000  0.000000  0.000000   

      think   thought       try     value  
0  0.311383  0.311383  0.000000  0.000000  
1  0.000000  0.000000  0.693642  0.346821  
2  0.000000  0.000000  0.000000  0.000000